-- ga4_streaming_schema.sql

CREATE TABLE your_dataset.your_ga4_streaming_table (
  event_name STRING,
  event_params ARRAY<STRUCT<key STRING, value STRING, int_value INT64, float_value FLOAT64, double_value FLOAT64, string_value STRING, items ARRAY<STRUCT<item_id STRING, item_name STRING, item_category STRING, quantity INT64, price FLOAT64, value_in_usd FLOAT64, coupon STRING, affiliation STRING, location_id STRING, start_date STRING, end_date STRING>>, currency STRING, item_id STRING, item_name STRING, item_category STRING, quantity INT64, price FLOAT64, value_in_usd FLOAT64, coupon STRING, affiliation STRING, checkout_step INT64, checkout_option STRING, discount FLOAT64, item_location_id STRING, item_brand STRING, item_variant STRING, promotion_id STRING, promotion_name STRING, creative_name STRING, creative_slot STRING, location_id STRING, index INT64, destination STRING, start_date STRING, end_date STRING>>,
  user_id STRING,
  user_pseudo_id STRING,
  timestamp_micros TIMESTAMP,
  event_date STRING,
  user_agent STRING,
  platform STRING,
  device_category STRING,
  geo_region STRING,
  geo_city STRING,
  geo_country STRING,
  traffic_source_source STRING,
  traffic_source_medium STRING,
  traffic_source_campaign STRING,
  traffic_source_keyword STRING,
  traffic_source_ad_content STRING,
  page_location STRING,
  page_referrer STRING,
  page_title STRING,
  page_hostname STRING,
  page_path STRING,
  ecommerce_purchase_revenue_usd FLOAT64,
  ecommerce_purchase_id STRING,
  ecommerce_transaction_id STRING,
  ecommerce_items ARRAY<STRUCT<item_id STRING, item_name STRING, item_category STRING, quantity INT64, price FLOAT64, value_in_usd FLOAT64, coupon STRING, affiliation STRING, location_id STRING, start_date STRING, end_date STRING>>,
  ecommerce_currency STRING,
  ecommerce_affiliation STRING,
  ecommerce_coupon STRING,
  ecommerce_checkout_step INT64,
  ecommerce_checkout_option STRING,
  ecommerce_discount FLOAT64,
  ecommerce_tax FLOAT64,
  ecommerce_shipping FLOAT64,
  user_ltv FLOAT64
  -- Add more fields as needed
);
